### ISSUE TITLE
希望可以使用zip压缩，对windows用户比较友好

### ISSUE THREAD

**Issue by wang001** [thunlp/OpenHowNet-API#1]
tar分块压缩在windows下很麻烦，谢谢大佬。

**Comment by yangalan123** [comment]
您好，感谢您对我们项目的关注！
1）Windows下分卷合并可以使用Copy /b命令（cmd)
2）tar格式在windows下处理可以使用[Bandizip](https://cn.bandisoft.com/bandizip/) 或者 [7-zip](https://www.7-zip.org/)进行解压
3）zip格式的文件：[pack.zip](https://pan.baidu.com/s/1JZezGUyEdaZner_0wxExgw), [dict.zip](https://pan.baidu.com/s/1qgzS7p3F1_QdYbrxdHNQaw)

**Comment by wang001** [comment]
可是我在powershell下调用cat生成tar后，用tar -xf pack.tar会报错。

**Comment by yangalan123** [comment]
您好，我们刚刚上传了zip格式的文件，您现在可以下载了

**Comment by wang001** [comment]
谢谢！

**Comment by yangalan123** [comment]
不客气，您先下载尝试使用，如果有任何问题，欢迎再在这里提问。

**Comment by yangalan123** [comment]
已经超过一个月没有收到您的答复，请问后续是否有遇到什么问题？如果有，请告知我们。若无回复，我将在一周后关闭此issue。
