### ISSUE TITLE
python3.6的脚本中运行到OpenHowNet.download()一行，出现“assertionError”错误

### ISSUE THREAD

**Issue by JiangYanting** [thunlp/OpenHowNet-API#10]
python3.6的脚本中运行到OpenHowNet.download()一行，开始出现下载data的进度条，然后出现了“assertionError”错误，请问这是为什么呢？

**Comment by dozbear** [comment]
请提供具体的错误信息

**Comment by JiangYanting** [comment]
> 
> 
> 请提供具体的错误信息

在服务器上运行了一下，问题已经解决！还是非常感谢~
