### ISSUE TITLE
知网核心数据下载不了

### ISSUE THREAD

**Issue by orangefly0214** [thunlp/OpenHowNet-API#11]
https://openhownet.thunlp.org/verified_download
请问下OpenHowNet官网认证后下载知网核心数据下载不了是什么原因呢？

**Comment by Fanchao-Qi** [comment]
请直接从Github下载压缩包后解压即可：
[HowNet.txt.zip](https://github.com/thunlp/OpenHowNet/blob/master/HowNet.txt.zip)

**Comment by orangefly0214** [comment]
好的，感谢！发自我的华为手机-------- 原始邮件 --------主题：Re: [thunlp/OpenHowNet] 知网核心数据下载不了 (#11)发件人：Fanchao Qi 收件人：thunlp/OpenHowNet 抄送：lychee ,Author 请直接从Github下载压缩包后解压即可：

HowNet.txt.zip

**Comment by ReadyTeresa** [comment]
> 请直接从Github下载压缩包后解压即可：
> [HowNet.txt.zip](https://github.com/thunlp/OpenHowNet/blob/master/HowNet.txt.zip)

这个地址找不到了
