### ISSUE TITLE
关于hownet词的义原标注格式的说明

### ISSUE THREAD

**Issue by liwenju0** [thunlp/OpenHowNet-API#12]
目前，我只在一篇2002年的论文中看到相关的说明《基于《知网》的词汇语义相似度计算 》。感觉有点过时。项目官网上也没有最新的说明文档。

**Comment by Fanchao-Qi** [comment]
你好，关于HowNet的标注格式，可以参考这篇文档：

> KDML — Knowledge Database Mark-up Language. Zhendong Dong and Qiang Dong. [[pdf (Chinese)](http://www.keenage.com/Theory%20and%20practice%20of%20HowNet/07.pdf)]

更多和HowNet相关的论文请参考这个论文列表：

> [Must-read Papers on Sememe Computation](https://github.com/thunlp/SCPapers)

**Comment by liwenju0** [comment]
谢谢
