### ISSUE TITLE
Synonym extraction based on similarity

### ISSUE THREAD

**Issue by jind11** [thunlp/OpenHowNet-API#13]
Hi, I am pretty interested in looking into the synonym extractions based on the sememe tree similarity using HowNet. I am wondering whether you or the original authors of the HowNet have benchmarked this method on some standard similarity evaluation dataset such as the SimLex-999 dataset and compared this method with some other popular methods for synonym extractions such as counter-fitting word embeddings. It would be great to have your thoughts on this topic. Thanks a lot!

**Comment by Fanchao-Qi** [comment]
Hi, we haven't evaluated the sememe-based word similarity computation method on English datasets. In fact, there are some "old" papers that focus on Chinese word similarity computation with the help of sememes, e.g., Liu et al. 2002 [[pdf](http://nlp.ict.ac.cn/ictnlp_website/wp-content/uploads/2020/05/%E5%9F%BA%E4%BA%8E%E3%80%8A%E7%9F%A5%E7%BD%91%E3%80%8B%E7%9A%84%E8%AF%8D%E6%B1%87%E8%AF%AD%E4%B9%89%E7%9B%B8%E4%BC%BC%E5%BA%A6%E8%AE%A1%E7%AE%97.pdf)], and Liu et al. 2013 [[pdf](https://www.aclweb.org/anthology/I13-1120.pdf)]. But to the best of our knowledge, no previous work tries experimenting on English.
