### ISSUE TITLE
核心数据下载链接丢失；知网官网无法进入

### ISSUE THREAD

**Issue by hjhcs121** [thunlp/OpenHowNet-API#17]
为什么都不能用了，出什么问题了

**Comment by Fanchao-Qi** [comment]
你好，知网官网 http://www.keenage.com/ 由董振东董强先生父子运营，目前确实无法访问，可能已停止运营。
自2019年起，知网核心数据已通过THUNLP进行开源，可以在[OpenHowNet网站](https://openhownet.thunlp.org)中进行词语义原的在线查询，同时原始数据文件可以在本repo中可以下载，即 [HowNet_Dict.zip](https://github.com/thunlp/OpenHowNet/blob/master/HowNet_Dict.zip).

**Comment by hjhcs121** [comment]
知道了，谢谢！
