### ISSUE TITLE
关于义原的role

### ISSUE THREAD

**Issue by Lele-Xie** [thunlp/OpenHowNet-API#18]
用API hownet_dict.get_sememes_by_word("苹果",structured=True)[0]["tree"]返回的结果里面有个“role”key，请教下，这个是描述义原间关系的吗？这个roles是否是闭集，是否有API可以直接查询义原间的role呢？

**Comment by Fanchao-Qi** [comment]
是的，这是义原间的动态角色标注。这是一个闭集。你用的这个函数就是可以得到义原之间的动态角色的呀，要注意的是相同的两个义原在不同的词中出现时其动态角色理论上可能不同，因此不能脱离词语的义原标注来谈论义原之间的动态角色。

**Comment by Lele-Xie** [comment]
> 是的，这是义原间的动态角色标注。这是一个闭集。你用的这个函数就是可以得到义原之间的动态角色的呀，要注意的是相同的两个义原在不同的词中出现时其动态角色理论上可能不同，因此不能脱离词语的义原标注来谈论义原之间的动态角色。

你好，感谢你的回复。请问这个义原间的动态角色是什么含义，可否简单举个例子，因为不是语言学专业，对这个不是很懂。另外，是否有函数可以直接获得所有的动态角色（一个集合）。
