### ISSUE TITLE
义原解析

### ISSUE THREAD

**Issue by ZTurboX** [thunlp/OpenHowNet-API#19]
如何把义原对应到ＰａｒｔＰｏｓｉ－ｔｉｏｎ、ｄｏｍａｉｎ、ｗｈｏｌｅ、ｈｏｓｔ和 ｍｏｄｉｆｉｅｒ

**Comment by ZTurboX** [comment]
也就是把主义原和5个辅助义原区分开来并对应

**Comment by Fanchao-Qi** [comment]
请参考README中的[这一部分](https://github.com/thunlp/OpenHowNet#get-structured-sememe-trees-for-certain-words-in-hownet)。
