### ISSUE TITLE
hownet版本问题

### ISSUE THREAD

**Issue by xiaopp123** [thunlp/OpenHowNet-API#2]
您好，请问这里面的是2012版的hownet吗？它和2011版有多大区别？我看一篇论文里用2011版，词的ID与这个hownet里不一致。

**Comment by yangalan123** [comment]
您好，我们使用的是由语知科技提供的新版本hownet，这一版本中有较多的义原标注发生变动，推荐使用我们的新版本数据。

**Comment by xiaopp123** [comment]
您好，请问哪里可以获取老版本的hownet呢？

**Comment by Fanchao-Qi** [comment]
你好，据我们所知HowNet每年都会更新，我们目前也没有其他版本。

> 您好，请问哪里可以获取老版本的hownet呢？

**Comment by ChengguoSu** [comment]
在Standards.py第195行中可能因为数据格式问题存在bug，item可能是list而非dict，如 item = [{'Def':'{}'}]

**Comment by yangalan123** [comment]
您好 @ChengguoSu ，非常感谢您对我们工作的关注和支持，我们已经收到您的反馈，正在排查问题，方便的话能请问一下您发现问题的具体使用场景吗？这将有助于我们更快发现并解决问题

**Comment by yangalan123** [comment]
问题已经发现：当使用“*”通配符时，get_sememes_by_word行为定义出错。感谢反馈，我们将尽快解决这个问题。

**Comment by yangalan123** [comment]
我们在新的[commit](https://github.com/thunlp/OpenHowNet-API/tree/5d9c04d4f2086fe736934a9e5af1e341e72ba9bd)中已经修复了此问题，感谢您的反馈和支持，希望您继续关注和支持OpenHowNet

**Comment by yangalan123** [comment]
已经过了一个半月没有回复，我将关闭这个issue，如果有任何需要，欢迎再次打开本issue。
