### ISSUE TITLE
如何查询所有英文义原？

### ISSUE THREAD

**Issue by Lele-Xie** [thunlp/OpenHowNet-API#21]
你好，API提供的get_all_semems()好像只能得到所有中文的义原，如果是要获得所有英文义原，要怎么处理呢？

**Comment by Fanchao-Qi** [comment]
你好，目前的版本还不支持。
我们近期会发布2.0版本，届时将支持此功能。

**Comment by zt991211** [comment]
您好，请问中英文的sememe都是同一套的吗？有相互之间的翻译词典吗？

**Comment by lvcc2018** [comment]
您好，目前OpenHowNet2.0版本已经发布，新版中可以通过相关API获得所有的义原实例，进而得到每个义原的中文和英文表述。
