### ISSUE TITLE
计算词语相似度，当输入为英语时，显示not annotated.

### ISSUE THREAD

**Issue by a328223290** [thunlp/OpenHowNet-API#23]
我尝试用calculate_word_similarity函数去进行相似度计算，但输入为英文词汇时，总是提示英语单词not annotated。请问这个问题该怎么解决呀。

**Comment by lvcc2018** [comment]
您好，新的OpenHowNet已经发布，对于您的问题有以下方法可以尝试：
1. 对英文词语进行词形还原后进行查找和计算；
2. 对于不确定的词语进行查询和计算时，可以设置相关函数的strict参数进行模糊查找；
3. 使用get_en_words()可以获得所有进行了义原标注的英文词，使用其中的词语进行计算。
