### ISSUE TITLE
一个义原标注小错误

### ISSUE THREAD

**Issue by ruowenWu** [thunlp/OpenHowNet-API#25]
您好，我在进行义原中英文对照的时候发现本来就对应中文义原“文莱”的英文义原“Brunei”还有对应了另一个中文义原“乌干达”。我在OpenHowNet/OpenHowNet/HowNet_dict.zip文件中也找到了源头：（从HowNet_original_new.txt文件第2032729行开始）

NO.=169394
W_C=乌干达先令
G_C=noun [2unit] [wu1 gan1 da2 xian1 ling4]
S_C=
E_C=
W_E=New Uganda Shilling
G_E=noun [53Shillingnoun-0unit00    ]
S_E=
E_E=
DEF={money|货币:belong="Brunei|乌干达",domain={commerce|商业}{finance|金融}}
RMK=

Brunei应该是专指文莱的专有名词。

**Comment by lvcc2018** [comment]
您好，新版OpenHowNet已经发布，我们对义原数据进行了更新，同时改正了该问题。
