### ISSUE TITLE
知网中的单词没有注音吗

### ISSUE THREAD

**Issue by RyanLiut** [thunlp/OpenHowNet-API#29]
请问可以将拼音也加在hownet里面的单词上面吗？一般意思确定了，单词的注音也确定了。知道了注音也可以帮助我们做一些其他的事情。

**Comment by Fanchao-Qi** [comment]
原版hownet中并无拼音信息，考虑到多音字的问题，必须人工校对才能确保拼音的准确性 —— 这个短时间内不太会进行。
