### ISSUE TITLE
OpenHowNet 是否只能用于研究，而不能商用？

### ISSUE THREAD

**Issue by gitathrun** [thunlp/OpenHowNet-API#3]
您好，之前查看知网信息的时候，发现知网的licence指明不能商用，所以没有继续跟进学习。

目前OpenHowNet我发现是MIT Licence，是不是说OpenHowNet是可以被用于商业软件开发了？

**Comment by yangalan123** [comment]
您好，十分感谢您对OpenHowNet的关注。我们与知网(HowNet)合作开源的OpenHowNet包含了HowNet的核心数据部分。在遵守开源协议的前提下，您可以将OpenHowNet的数据和API用于研究和商用。

**Comment by gitathrun** [comment]
@yangalan123 谢谢您的回复，我相信知网在商业界一定会有更大的成就，占有自己的一席之地。

Good Luck!
