### ISSUE TITLE
sememe_sim_table.pkl

### ISSUE THREAD

**Issue by tanyang** [thunlp/OpenHowNet-API#4]
这个相似度是如何构建的？

**Comment by yangalan123** [comment]
这里我们用的是基于义原结构的相似度，相关计算方式请参考：
"Jiangming Liu, Jinan Xu, Yujie Zhang. An Approach of Hybrid Hierarchical Structure for Word Similarity Computing by HowNet. In Proceedings of IJCNLP"

**Comment by tanyang** [comment]
OK，谢谢哈

**Comment by crazyFoolLh** [comment]
> 这里我们用的是基于义原结构的相似度，相关计算方式请参考：
> "Jiangming Liu, Jinan Xu, Yujie Zhang. An Approach of Hybrid Hierarchical Structure for Word Similarity Computing by HowNet. In Proceedings of IJCNLP"

你好，我看了实现代码和这篇论文的实现原理，是不是在计算义原相似度的时候，只考虑了结构相似度，略去了定义相似度。后续还会将义原的定义相似度考虑进去吗？

**Comment by yangalan123** [comment]
您好，非常感谢您的反馈。我们会在未来调研基于义原定义的义原相似度，目前没有看到相关的比较成熟的工作，如果您有看到相关工作，欢迎推荐给我们参考。需要说明的是，本仓库主要维护OpenHowNet API的较为成熟的而通用的功能，所以当新功能未充分测试前不会上线（当然，我们欢迎大家提供Pull Request，新的PR一样需要通过测试才会并入仓库）。
