### ISSUE TITLE
生成的pickle文件夹下的三个文件是错误的

### ISSUE THREAD

**Issue by crazyFoolLh** [thunlp/OpenHowNet-API#5]
我在使用解压到pickle文件夹下的hownet.pkl这个文件的时候，发现一些词返回的义项树是空的，只包含第一个义素，后边的children是空的，然后一些词的相似度排序也明显的不对，比如“男人”，返回的词是一些诸如“伕”、“伕役”、“俤”这样的词。
然后，我执行submit_user文件夹下的main.py文件重新生成了hownet.pkl等文件，义项树就不是空的了，“男人”的相似词也正常了。

**Comment by yangalan123** [comment]
感谢您的反馈，正在确认问题中。

**Comment by yangalan123** [comment]
很抱歉这么晚回复您，我们这边实验发现没有问题，可否把您当时使用的pickle文件夹打包给我邮箱传一下？我的邮箱是yangalan1996@gmail.com

**Comment by crazyFoolLh** [comment]
已发送，请查收~

**Comment by yangalan123** [comment]
抱歉这么长时间回复您，不知道您的问题是否得到解决？我们经过尝试（包括使用虚拟机模拟）仍然无法复现您的问题，也许您可以考虑将您的OS镜像给我一份？
