### ISSUE TITLE
OpenHowNet的sense问题

### ISSUE THREAD

**Issue by SummerDay231** [thunlp/OpenHowNet-API#6]
能否用OpenHowNet查询到每个sense对应的embedding呢？我找到了Improved Word Representation Learning with Sememes 这篇文章的一些学习结果，但是义项数目和相应的义原和OpenHowNet不是完全对应的，如果我想用OpenHowNet标注的义项，能否有什么方法可以获取它的embedding向量呢？

**Comment by yangalan123** [comment]
您好，OpenHowNet-API目前未搭载根据sense查询embedding的功能，一方面因为这是知识库的应用工作，不属于本Repo的工作范围，另一方面也是因为embedding文件太大不方便上传GitHub。您说的这篇文章当时使用的是HowNet 2017版本的数据的一部分，修正的代码和预训练的sense embedding可以在[这里](https://github.com/thunlp/SE-WRL-SAT)找到（预训练的文件的具体下载地址：[link](https://cloud.tsinghua.edu.cn/d/76ab4a71efa541bd8eb3/)。非常感谢您对我们工作的关注与支持！
