### ISSUE TITLE
请问可以开源最新上下位关系吗

### ISSUE THREAD

**Issue by Vicky-Meng** [thunlp/OpenHowNet-API#7]
请问Hownet中的上下位关系有开源吗, 包括实体上下位,事件上下位, 属性上下位等

**Comment by yangalan123** [comment]
pack.tar/pack.zip解压后，可以到pack\submit_user\data下找到一系列taxonomy文件，这些文件就描述了HowNet中的各种上下位关系。这里为了尽可能减少项目大小以符合Github的文件上传要求所以一起打包了。

**Comment by Vicky-Meng** [comment]
十分感谢~
还想问一下, 还有其他的数据内容吗, 比如 
知网事件关系与角色转换(HowNet EventRoleShift.txt),
知网对义表\反义表,(HowNet Taxonomy Converse.txt\HowNet Taxonomy Antonym.txt) 
语法特征表(HowNet Taxonomy Syntax.txt), 
动态角色与语用特征表(HowNet Taxonomy EventRoleAndFeature.txt)
等

**Comment by yangalan123** [comment]
抱歉，您要求的这些文件我们目前还没有。我们将会在后续和知网沟通将这些文件开源出来。
