### ISSUE TITLE
python3.6.2 win10上hownet_dict.get_all_sememes() 有编码错误

### ISSUE THREAD

**Issue by onewaymyway** [thunlp/OpenHowNet-API#9]
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-14-e83fbc3eb9df> in <module>()
----> 1 hownet_dict.get_all_sememes()

~\Anaconda3\envs\tensorflow\lib\site-packages\OpenHowNet\Standards.py in get_all_sememes(self)
    247             package_directory = os.path.dirname(os.path.abspath(__file__))
    248             f = get_resource("sememe_all.txt", 'r')
--> 249             buf = f.readlines()[0]
    250             self.sememe_all = buf.strip().split()
    251             return self.sememe_all

UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 22: illegal multibyte sequence

get_resource函数里加上encoding参数才能对

**Comment by dozbear** [comment]
sememe_all.txt 应该是 utf-8 编码的，请尝试从 pypi 重新安装，再查看问题是否存在

**Comment by onewaymyway** [comment]
> sememe_all.txt 应该是 utf-8 编码的，请尝试从 pypi 重新安装，再查看问题是否存在

sememe_all.txt是utf-8编码，但是不传encoding的时候这种环境是默认用gbk去读取的，所以就出问题了
显式的在Download.py 的get_resource函数的open里面传编码的参数就能解决这个问题，不然就在这种环境下出问题
def get_resource(path, mode='r',encoding=None):
    try:
        package_directory = os.path.dirname(os.path.abspath(__file__))
        file = open(os.path.join(package_directory, path), mode,encoding=encoding)
        return file
    except FileNotFoundError as e:
        error_msg = str(
            "Important data file \"{}\" lost, please run `OpenHowNet.download()`."
        ).format(path)
        raise FileNotFoundError(error_msg)
